=== api-evangelist/activision-blizzard/json-schema/activision-blizzard-hearthstone-card-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/activision-blizzard/refs/heads/main/json-schema/activision-blizzard-hearthstone-card-schema.json",
  "title": "HearthstoneCard",
  "description": "A Hearthstone card",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "description": "Card ID",
      "example": 1234
    },
    "collectible": {
      "type": "integer",
      "description": "Whether the card is collectible (1=yes)",
      "example": 1
    },
    "slug": {
      "type": "string",
      "description": "Card slug",
      "example": "ragnaros-the-firelord"
    },
    "classId": {
      "type": "integer",
      "description": "Class ID",
      "example": 1
    },
    "multiClassIds": {
      "type": "array",
      "items": {
        "type": "integer"
      },
      "description": "Multi-class IDs"
    },
    "cardTypeId": {
      "type": "integer",
      "description": "Card type ID",
      "example": 4
    },
    "cardSetId": {
      "type": "integer",
      "description": "Card set ID",
      "example": 2
    },
    "rarityId": {
      "type": "integer",
      "description": "Rarity ID",
      "example": 5
    },
    "artistName": {
      "type": "string",
      "description": "Artist name",
      "example": "Alex Horley"
    },
    "health": {
      "type": "integer",
      "description": "Card health",
      "example": 8
    },
    "attack": {
      "type": "integer",
      "description": "Card attack",
      "example": 8
    },
    "manaCost": {
      "type": "integer",
      "description": "Mana cost",
      "example": 8
    },
    "name": {
      "type": "string",
      "description": "Card name",
      "example": "Ragnaros the Firelord"
    },
    "text": {
      "type": "string",
      "description": "Card text"
    },
    "image": {
      "type": "string",
      "format": "uri",
      "description": "Card image URL"
    },
    "imageGold": {
      "type": "string",
      "format": "uri",
      "description": "Gold card image URL"
    },
    "flavorText": {
      "type": "string",
      "description": "Card flavor text"
    },
    "cropImage": {
      "type": "string",
      "format": "uri",
      "description": "Cropped card image URL"
    }
  }
}

=== api-evangelist/activision-blizzard/examples/activision-blizzard-hearthstone-card-example.json
{
  "id": 1234,
  "collectible": 1,
  "slug": "ragnaros-the-firelord",
  "classId": 1,
  "multiClassIds": [
    42
  ],
  "cardTypeId": 4,
  "cardSetId": 2,
  "rarityId": 5,
  "artistName": "Alex Horley",
  "health": 8,
  "attack": 8,
  "manaCost": 8,
  "name": "Ragnaros the Firelord",
  "text": "example-value",
  "image": "https://example.com",
  "imageGold": "https://example.com",
  "flavorText": "example-value",
  "cropImage": "https://example.com"
}
